apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: voter-registration
  name: voter-registration
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voter-registration
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: voter-registration
    spec:
      containers:
      - image: sumitdas28/voter-registration-service:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: voter-registration-service
        readinessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/liveness
      restartPolicy: Always
---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: voter-registration
    name: voter-registration
    namespace: default
  spec:
    ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: voter-registration
    sessionAffinity: None
    type: LoadBalancer

