apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-submission
  name: vote-submission
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-submission
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vote-submission
    spec:
      containers:
      - image: sumitdas28/vote-submission-service:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: vote-submission-service
        env:
          - name: VOTER_REGISTRATION_URI
            value: http://voter-registration
        readinessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/liveness
      restartPolicy: Always
---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: vote-submission
    name: vote-submission
    namespace: default
  spec:
    ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
    selector:
      app: vote-submission
    sessionAffinity: None
    type: LoadBalancer